### ISSUE TITLE
CRS Issue

### ISSUE THREAD

**Issue by jlwoodr** [noaa-ocs-hydrography/vyperdatum#21]
Hello,

I was trying to run through the first example on the read me and keep getting the following error:

`CRSError: Invalid WKT string: NAD83`

I have also tried 'nad83' with no luck. I also looked through the crs.py code to find the list of acceptable strings and could not find anything. How should I go about debugging this? Thanks!

Johnathan

**Comment by Rjialceky** [comment]
Initial report is that it has to do with 0- vs 1-based indexing on datum string lookup.  For now, use explicit EPSG codes to specify geometric datum; e.g., in the first example, use EPSG integer code 6319 for 3D 'nad83':
`vp.transform_points(6319, 'mllw', x, y, z=z)`

**Comment by jlwoodr** [comment]
That worked great! Thanks for the help.

Johnathan Woodruff

**Comment by ericgyounkin** [comment]
@jlwoodr Our readme was very out of date.  I updated the examples to show the correct usage.  Thanks for letting us know!

Fixed in 600fc2f16fe5a95dc3a26336d5d8cd23421fef5f
